[package]
name = "grepclone"
version = "0.1.0"
authors = ["phanttien"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = "3"
owo-colors = "3.5.0"